-- Apply after variety_migration.sql. Re-run to add newly verified catalog entries.
INSERT INTO public.garden_varieties (variety_key, display_name) VALUES
('bobo','Bobo'),
('little_lime','Little Lime'),
('limelight','Limelight'),
('vanille_fraise','Vanille Fraise'),
('самарская_лидия','Самарская Лидия'),
('pinky_winky','Pinky Winky'),
('phantom','Phantom'),
('grandiflora','Grandiflora'),
('diamant_rouge','Diamant Rouge'),
('quick_fire','Quick Fire'),
('tardiva','Tardiva'),
('polar_bear','Polar Bear'),
('baby_lace','Baby Lace'),
('bonfire','Bonfire'),
('candlelight','Candlelight'),
('confetti','Confetti'),
('early_harry','Early Harry'),
('fire_light','Fire Light'),
('fraise_melba','Fraise Melba'),
('graffiti','Graffiti'),
('little_fresco','Little Fresco'),
('little_quick_fire','Little Quick Fire'),
('living_candy_love','Living Candy Love'),
('living_colourful_cocktail','Living Colourful Cocktail'),
('living_cotton_cream','Living Cotton Cream'),
('living_infinity','Living Infinity'),
('living_little_blossom','Living Little Blossom'),
('living_little_passion','Living Little Passion'),
('living_little_rosy','Living Little Rosy'),
('living_milk_honey','Living Milk & Honey'),
('living_pink_rose','Living Pink & Rose'),
('living_pinky_promise','Living Pinky Promise'),
('living_raspberry_pink','Living Raspberry Pink'),
('living_red_velvet','Living Red Velvet'),
('living_royal_flower','Living Royal Flower'),
('living_strawberry_blossom','Living Strawberry Blossom'),
('living_sugar_rush','Living Sugar Rush'),
('living_summer_snow','Living Summer Snow'),
('living_touch_of_pink','Living Touch of Pink'),
('pastelgreen','Pastelgreen'),
('pinkachu','Pinkachu'),
('redlight','Redlight'),
('skyfall','Skyfall'),
('jane','Jane'),
('savill_lace','Savill Lace'),
('kyushu','Kyushu'),
('altona','Altona'),
('bläuling','Bläuling'),
('blaumeise','Blaumeise'),
('brügg','Brügg'),
('colorado','Colorado'),
('dalian','Dalian'),
('étoile_violette','Étoile Violette'),
('générale_vicomtesse_de_vibraye','Générale Vicomtesse de Vibraye'),
('kardinal','Kardinal'),
('klaveren','Klaveren'),
('koria','Koria'),
('lanarth_white','Lanarth White'),
('libelle','Libelle'),
('madame_emile_mouillère','Madame Emile Mouillère'),
('magical_colourdream','Magical Colourdream'),
('magical_garnet','Magical Garnet'),
('magical_harmony','Magical Harmony'),
('magical_revolution','Magical Revolution'),
('magical_rhapsody','Magical Rhapsody'),
('magical_wings','Magical Wings'),
('mariesii_lilacina','Mariesii Lilacina'),
('möwe','Möwe'),
('nachtigall','Nachtigall'),
('parzifal','Parzifal'),
('pengwyn','Pengwyn'),
('rotschwanz','Rotschwanz'),
('schöne_bautznerin','Schöne Bautznerin'),
('together','Together'),
('tokyo_delight','Tokyo Delight'),
('trebah_silver','Trebah Silver'),
('veitchii','Veitchii'),
('wedding_gown','Wedding Gown'),
('zorro','Zorro'),
('beni_yama','Beni-yama'),
('bluebird','Bluebird'),
('diadem','Diadem'),
('fuji_no_taki','Fuji-no-taki'),
('grayswood','Grayswood'),
('kiyosumi','Kiyosumi'),
('miranda','Miranda'),
('miyama_yae_murasaki','Miyama-yae-murasaki'),
('rosalba','Rosalba'),
('shirofuji','Shirofuji'),
('shōjō','Shōjō'),
('tiara','Tiara'),
('anthony_bullivant','Anthony Bullivant'),
('hot_chocolate','Hot Chocolate'),
('macrophylla','Macrophylla'),
('peter_chappell','Peter Chappell'),
('velvet_and_lace','Velvet and Lace'),
('snow_queen','Snow Queen'),
('snowflake','Snowflake'),
('annabelle','Annabelle'),
('viridescens','Viridescens'),
('yohraku_tama','Yohraku-tama')
ON CONFLICT (variety_key) DO UPDATE SET display_name = EXCLUDED.display_name;
